### ISSUE TITLE
Add section on Revocation

### ISSUE THREAD

**Issue by msporny** [opencreds/vc-data-model#34]
It is currently not clear how Verifiable Claims may be revoked by the issuer. We should add a section to the specification that clarifies the various mechanisms for revocation of claims.

Discussion on this issue started here: https://github.com/opencreds/vc-use-cases/issues/33#issuecomment-273237017

**Comment by msporny** [comment]
ACTION: Manu to write section on Revocation for the Data Model spec.

**Comment by msporny** [comment]
This issue is waiting on reviews for the PR.

**Comment by burnburn** [comment]
Note that you will also need to add Syntax sections as well.  PR #36 only adds the model.

**Comment by msporny** [comment]
I added one example for the time being, we'll have to sort out what the syntax looks like via https://github.com/opencreds/vc-data-model/issues/35.
